name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/google_icon.png
    - assets/profile_photo.jpg
    - assets/fonts/Lato-Regular.ttf
    - assets/fonts/Lato-Bold.ttf
    - assets/fonts/Lato-Semibold.ttf  # Added since you have this file
  
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Semibold.ttf  # Optional: Add if you want to use semibold
          weight: 600